apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
spec:
  containers:
  - name: test-container
    image: nginx
    volumeDevices:
    - name: ephemeral-volume
      devicePath: /vol001
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.lvm.csi/node
            operator: In
            values:
            - harvester-node-2
  volumes:
  - name: ephemeral-volume
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: lvm-striped
          volumeMode: Block