apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-jammy-pod
spec:
  containers:
    - name: ubuntu-jammy-container
      image: ubuntu:jammy
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeDevices:
        - devicePath: "/volumes/vol001"
          name: vol001
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.lvm.csi/node
            operator: In
            values:
            - harvester-node-2
  volumes:
    - name: vol001
      persistentVolumeClaim:
        claimName: vol001