apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol002-clone
spec:
  storageClassName: lvm-dm-thin
  dataSource:
    name: vol001-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Block