apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol001-clone
spec:
  storageClassName: lvm-striped
  dataSource:
    name: vol001
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Block