apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol001
spec:
  storageClassName: lvm-striped
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Block