apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vol001-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: lvm-snapshot
  source:
    persistentVolumeClaimName: vol001