---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harvester-csi-driver-lvm
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: harvester-csi-driver-lvm
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "persistentvolumeclaims/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses", "volumesnapshots", "volumesnapshotcontents", "volumesnapshotcontents/status"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: harvester-csi-driver-lvm
subjects:
  - kind: ServiceAccount
    name: harvester-csi-driver-lvm
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: harvester-csi-driver-lvm
  apiGroup: rbac.authorization.k8s.io
---